#! /usr/bin/env node

path = require('path');
try {
    process.chdir(path.resolve(__dirname, ".."));
}
catch(e) {
    console.error(e + "\nCould not change dir :-(\nAborting");
    process.exit(1);
}

var twitter = require('twitter');
var conf = require('./config.json')

var twit = new twitter(conf.twitter)

console.log("Starting traftnrbot tracking " + conf.traftnr)
twit.stream('statuses/filter', conf.traftnr, function(stream) {
    stream.on('data', function(data) {
        if (data.user.screen_name != conf.screen_name)
        twit.retweetStatus(data.id_str, function(){
            console.log("RT @" + data.user.screen_name + ": " + data.text);
        });
    });
});
